/*
 * ============================================================
 *               ORIGIN LITE MODE — BACKEND ENGINE
 *         Balanced Mode (Safe, Clean, Pro-Compatible)
 * ============================================================
 *
 *   ALWAYS RETURNS:
 *
 *      backendSummary = {
 *        backendInfo: { ...numbers },
 *        summaryText: "string",
 *
 *        routes: { preview, total, proLocked },
 *        controllers: { preview, total, proLocked },
 *        services: { preview, total, proLocked },
 *        models: { preview, total, proLocked },
 *        utils: { preview, total, proLocked },
 *        middleware: { preview, total, proLocked },
 *        config: { preview, total, proLocked },
 *
 *        hints: { preview, total, proLocked }
 *      }
 *
 *   This engine is *Lite Mode safe* and does not crash.
 * ============================================================
 */

import fs from "fs-extra";
import path from "path";
import pc from "picocolors";

/* ============================================================
   BACKEND SCANNERS
   ============================================================ */
import { scanBackendRoutes } from "./scanner/routeScanner.js";
import { scanBackendControllers } from "./scanner/controllerScanner.js";
import { scanBackendServices } from "./scanner/serviceScanner.js";
import { scanBackendModels } from "./scanner/modelScanner.js";
import { scanBackendUtils } from "./scanner/utilsScanner.js";
import { scanBackendMiddlewares } from "./scanner/middlewareScanner.js";
import { scanBackendConfig } from "./scanner/configScanner.js";

/* ============================================================
   BACKEND HINT SYSTEM
   ============================================================ */
import { scanBackendHints } from "./backendHintEngine.js";

/* ============================================================
   SAFE NORMALIZER
   ============================================================ */
function normalize(obj) {
  if (!obj || typeof obj !== "object") {
    return { preview: [], total: 0, proLocked: 0 };
  }

  return {
    preview: Array.isArray(obj.preview) ? obj.preview : [],
    total: typeof obj.total === "number" ? obj.total : 0,
    proLocked: typeof obj.proLocked === "number" ? obj.proLocked : 0,
  };
}

/* ============================================================
   FRAMEWORK DETECTOR
   ============================================================ */
function detectBackendFramework(root) {
  const pkgFile = path.join(root, "package.json");
  if (!fs.existsSync(pkgFile)) return "Unknown";

  try {
    const pkg = fs.readJsonSync(pkgFile);

    const deps = { ...pkg.dependencies, ...pkg.devDependencies };

    if (!deps) return "Unknown";

    if (deps.express) return "Express";
    if (deps.fastify) return "Fastify";
    if (deps["@nestjs/core"]) return "NestJS";
    if (deps.hono) return "Hono";
  } catch (err) {}

  return "Unknown";
}

/* ============================================================
   HEALTH SCORE (Lite — Safe)
   ============================================================ */
function computeBackendHealth({ routes, controllers, services, models }) {
  let score = 100;

  if (routes.total === 0) score -= 20;
  if (controllers.total === 0) score -= 15;
  if (models.total === 0) score -= 20;
  if (services.total === 0) score -= 10;

  if (score < 1) score = 1;
  return score;
}

/* ============================================================
   SUMMARY MARKDOWN (Used by BE + FS Modes)
   ============================================================ */
function buildBackendSummaryText(info, blocks) {
  const {
    framework,
    routes,
    controllers,
    services,
    models,
    utils,
    middleware,
    configFiles,
    health,
  } = info;

  const { ROUTES, CONTROLLERS, SERVICES, MODELS, UTILS, MIDDLEWARE, CONFIG } =
    blocks;

  return `
# 🟦 Backend Summary (Lite)

**Framework:** ${framework}  
**Health:** ${health}%

---

## 📌 Routes (${routes})
${
  ROUTES.preview.length
    ? ROUTES.preview.map((r) => "- " + r).join("\n")
    : "_None_"
}

---

## 📌 Controllers (${controllers})
${CONTROLLERS.preview.length ? CONTROLLERS.preview.join("\n") : "_None_"}

---

## 📌 Services (${services})
${SERVICES.preview.length ? SERVICES.preview.join("\n") : "_None_"}

---

## 📌 Models (${models})
${MODELS.preview.length ? MODELS.preview.join("\n") : "_None_"}

---

## 📌 Utils (${utils})
${UTILS.preview.length ? UTILS.preview.join("\n") : "_None_"}

---

## 📌 Middleware (${middleware})
${MIDDLEWARE.preview.length ? MIDDLEWARE.preview.join("\n") : "_None_"}

---

## 📌 Config Files (${configFiles})
${CONFIG.preview.length ? CONFIG.preview.join("\n") : "_None_"}

---

Generated by **Origin Lite Mode**
`;
}

/* ============================================================
   MAIN BACKEND SUMMARY ENGINE
   ============================================================ */
export function generateBackendSummary(root) {
  /* --- ALWAYS NORMALIZED --- */
  const ROUTES = normalize(scanBackendRoutes(root));
  const CONTROLLERS = normalize(scanBackendControllers(root));
  const SERVICES = normalize(scanBackendServices(root));
  const MODELS = normalize(scanBackendModels(root));
  const UTILS = normalize(scanBackendUtils(root));
  const MIDDLEWARE = normalize(scanBackendMiddlewares(root));
  const CONFIG = normalize(scanBackendConfig(root));

  /* --- FRAMEWORK --- */
  const framework = detectBackendFramework(root);

  /* --- HEALTH --- */
  const backendInfo = {
    framework,
    routes: ROUTES.total,
    controllers: CONTROLLERS.total,
    services: SERVICES.total,
    models: MODELS.total,
    utils: UTILS.total,
    middleware: MIDDLEWARE.total,
    configFiles: CONFIG.total,
    health: computeBackendHealth({
      routes: ROUTES,
      controllers: CONTROLLERS,
      services: SERVICES,
      models: MODELS,
    }),
  };

  /* --- HINTS --- */
  const HINTS = normalize(
    scanBackendHints(root, {
      routes: ROUTES,
      controllers: CONTROLLERS,
      services: SERVICES,
      models: MODELS,
      utils: UTILS,
      middleware: MIDDLEWARE,
    })
  );

  /* --- MARKDOWN TEXT --- */
  const summaryText = buildBackendSummaryText(backendInfo, {
    ROUTES,
    CONTROLLERS,
    SERVICES,
    MODELS,
    UTILS,
    MIDDLEWARE,
    CONFIG,
  });

  /* --- FINAL RETURN SHAPE --- */
  return {
    backendInfo,
    summaryText,

    routes: ROUTES,
    controllers: CONTROLLERS,
    services: SERVICES,
    models: MODELS,
    utils: UTILS,
    middleware: MIDDLEWARE,
    config: CONFIG,

    hints: HINTS,
  };
}

export default generateBackendSummary;
