import fs from "fs-extra";
import path from "path";

/**
 * Simple AI Bridge Summary Generator (Free Tier)
 * Produces a clean summary for the user.
 */
export async function generateBridgeSummary(projectDir) {
  const aiDir = path.join(projectDir, "docs", "ai");
  await fs.ensureDir(aiDir);

  const bridge = safeRead(path.join(aiDir, "bridge.json"));
  const flow = safeRead(path.join(aiDir, "flow_state.json"));
  const rhythm = safeRead(path.join(aiDir, "rhythm_summary.json"));
  const reflection = safeRead(path.join(aiDir, "latest_reflection.json"));

  const md = [];

  // ---------------------------------------------------------
  // HEADER
  // ---------------------------------------------------------
  md.push(`# 🤖 Origin Bridge Summary (Free Tier)`);
  md.push(`Generated: **${new Date().toISOString()}**`);
  md.push(``);

  // ---------------------------------------------------------
  // REFLECTION
  // ---------------------------------------------------------
  md.push(`## 📝 Latest Reflection`);
  md.push(
    reflection?.reflection ? `> _${reflection.reflection}_` : `_None recorded_`
  );
  md.push(``);

  // ---------------------------------------------------------
  // FLOW
  // ---------------------------------------------------------
  md.push(`## 🌊 Flow State`);
  md.push(`- Mode: **${flow?.mode || "Unknown"}**`);
  md.push(`- Time: ${flow?.time || "—"}`);
  md.push(``);

  // ---------------------------------------------------------
  // RHYTHM
  // ---------------------------------------------------------
  md.push(`## ⏱ Coding Rhythm`);
  if (rhythm?.hours) {
    const peakHour = rhythm.hours.indexOf(Math.max(...rhythm.hours));
    md.push(`- Strongest Hour: **${peakHour}:00**`);
  } else {
    md.push(`_No rhythm data yet_`);
  }
  md.push(``);

  // ---------------------------------------------------------
  // BRIDGE
  // ---------------------------------------------------------
  md.push(`## 🔗 Bridge Data`);
  md.push(bridge ? `Bridge file exists` : `No bridge data yet`);
  md.push(``);

  // ---------------------------------------------------------
  // FOOTER
  // ---------------------------------------------------------
  md.push(`---`);
  md.push(`_Generated by Origin Free Tier_`);

  await fs.writeFile(path.join(aiDir, "bridge_summary.md"), md.join("\n"));
}

/**
 * R4+ backward-compatible wrapper
 * Required by auditEngine.js
 */
export async function generateSummaryV3(projectDir, latestDrift = {}) {
  return generateBridgeSummary(projectDir, latestDrift);
}

/**
 * Safe JSON reader
 */
function safeRead(file) {
  try {
    if (!fs.existsSync(file)) return null;
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}
