/*
 * ─────────────────────────────────────────────────────────────
 *                       ORIGIN LITE MODE
 *                       INTERNAL MODULE
 * ─────────────────────────────────────────────────────────────
 *
 *  WARNING:
 *  This file is part of Origin Lite Mode’s internal scanning
 *  engine. It is not a public API and not designed for reuse,
 *  modification, or redistribution.
 *
 *  Changing, copying, or altering this file may cause:
 *    • auditEngine failure
 *    • incorrect scan results
 *    • unstable CLI behavior
 *    • loss of Lite Mode protections
 *    • invalid preview generation
 *
 *  The full, stable, and extended scanning engine is available
 *  ONLY in Origin Pro. Lite Mode contains intentionally limited
 *  and obfuscated logic for security and upgrade protection.
 *
 *  Proceed at your own risk. This module is NOT considered a
 *  stable API surface and may break without notice.
 *
 *  © Dipz Origin — Protected Internal Logic
 * ─────────────────────────────────────────────────────────────
 */

// ===========================================================
// HEALTH SCORE CALCULATOR (Lite Mode Simple Version)
// ===========================================================
export function computeHealthScore({ features, ui, hints, framework }) {
  let score = 100;

  if (!framework) score -= 20;
  if (hints.length > 0) score -= Math.min(20, hints.length * 5);
  if (features.length === 0) score -= 10;
  if (ui.length === 0) score -= 10;

  if (score < 0) score = 0;
  return score;
}

// ===========================================================
// MARKDOWN SUMMARY (Lite Mode)
// ===========================================================
export function generateSummary({
  project,
  files,
  framework,
  components,
  pages,
  features,
  ui,
  hints,
  backendExists,
  relationships,
  relationshipsTotal,
  duplicates,
  deadFiles,
  unusedDeps,
  timestamp,
}) {
  const more = (arr, previewCount) =>
    arr.length > previewCount ? `+${arr.length - previewCount} more (Pro)` : "";

  return `
# Origin Lite Summary

Generated: ${timestamp}

## Overview
Project: **${project}**
Files scanned: **${files.length}**
Framework: **${framework}**

---

## Components (Preview)
${components.slice(0, 10).join("\n")}
${more(components, 10)}

## Pages (Preview)
${pages.slice(0, 10).join("\n")}
${more(pages, 10)}

## Features (Preview)
${features.slice(0, 10).join("\n")}
${more(features, 10)}

## UI System
${ui.length ? ui.map((u) => `- ${u}`).join("\n") : "None detected"}

${
  backendExists
    ? `
## Backend (Preview)
Detected backend folder — Lite Mode does not scan backend yet.
(Full backend analysis available in a future update.)

---`
    : ""
}

## Component Relationships (Preview)
${relationships.length ? relationships.join("\n") : "None found"}
${
  relationshipsTotal > relationships.length
    ? `\n+${relationshipsTotal - relationships.length} more (Pro)`
    : ""
}

## Possible Duplicates (Preview)
${duplicates.preview.length ? duplicates.preview.join("\n") : "None detected"}
${
  duplicates.total > duplicates.preview.length
    ? `\n+${duplicates.total - duplicates.preview.length} more (Pro)`
    : ""
}

## Dead Files (Preview)
${deadFiles.preview.length ? deadFiles.preview.join("\n") : "None detected"}
${
  deadFiles.total > deadFiles.preview.length
    ? `\n+${deadFiles.total - deadFiles.preview.length} more (Pro)`
    : ""
}

## Unused Dependencies (Preview)
${unusedDeps.preview.length ? unusedDeps.preview.join("\n") : "None detected"}
${
  unusedDeps.total > unusedDeps.preview.length
    ? `\n+${unusedDeps.total - unusedDeps.preview.length} more (Pro)`
    : ""
}

## Structure Hints (Lite)
${hints.length ? hints.join("\n") : "No structural issues detected."}

---

_Generated by Origin Lite Mode_
`;
}
