/*
 * ============================================================
 *     ORIGIN LITE MODE — FULLSTACK SUMMARY ENGINE (FINAL)
 *  Clean • Balanced • Fully Compatible with Lite Audit Engine
 * ============================================================
 *
 *  This engine generates bridge_summary.md when BOTH
 *  frontend + backend structures exist.
 *
 *  It MUST match:
 *    - auditEngine frontendSummary format
 *    - backendSummaryEngine normalized structure
 *
 *  Output: clean Lite summary + Pro previews.
 * ============================================================
 */

import fs from "fs-extra";

/* ============================================================
   Helper: Render a capped list safely
   ============================================================ */
function renderBlock(label, block) {
  if (!block || !Array.isArray(block.preview)) {
    return `### ${label}\nNone\n`;
  }

  let text = `### ${label}\n`;

  block.preview.forEach((item) => (text += `- ${item}\n`));

  if (block.proLocked > 0) {
    text += `+${block.proLocked} more (Pro)\n`;
  }

  text += "\n";
  return text;
}

/* ============================================================
   FULLSTACK SUMMARY ENGINE (FINAL)
   ============================================================ */
export function generateFullstackSummary({ frontend, backend }) {
  const {
    framework: feFramework,
    pages,
    components,
    features,
    ui,
    hints: feHints,
    meta,
    health: feHealth,
  } = frontend;

  const {
    backendInfo,
    routes,
    controllers,
    services,
    middleware,
    models,
    utils,
    config,
    summaryText, // raw BE markdown if needed in Pro
  } = backend;

  const beHealth = backendInfo.health;
  const overall = Math.round((feHealth + beHealth) / 2);

  /* ============================================================
     BUILD MARKDOWN
     ============================================================ */
  let out = `
# 🟣 Origin Lite — Fullstack Summary

## 🧠 Project Overview
- Architecture: **Fullstack**
- Frontend Framework: **${feFramework}**
- Backend Framework: **${backendInfo.framework}**
- Frontend Health: **${feHealth}%**
- Backend Health: **${beHealth}%**
- Overall Health: **${overall}%**

---

# 🎨 Frontend Snapshot (Lite)

## Pages (Preview)
${pages.length ? pages.map((p) => "- " + p).join("\n") : "None"}

## Features (Preview)
${features.length ? features.map((f) => "- " + f).join("\n") : "None"}

## Components (Preview)
${
  components.length
    ? components
        .slice(0, 6)
        .map((c) => "- " + c)
        .join("\n") +
      (components.length > 6
        ? `\n+${components.length - 6} more (Pro)\n`
        : "\n")
    : "None\n"
}

## UI Systems
${ui.length ? ui.map((u) => "- " + u).join("\n") : "None"}

## FE Structure Hints (Lite)
${feHints.length ? feHints.map((h) => "- " + h).join("\n") : "None"}

---

# 🔧 Backend Snapshot (Lite)

${renderBlock("API Routes (Preview)", routes)}
${renderBlock("Controllers", controllers)}
${renderBlock("Services", services)}
${renderBlock("Middleware", middleware)}
${renderBlock("Models", models)}
${renderBlock("Utils", utils)}
${renderBlock("Config Files", config)}

---

# 🔗 Fullstack Insights (Lite)
- Detected frontend + backend structure.
- FE pages/components aligned alongside BE API.
- No FE⇄BE mapping in Lite Mode.
- **Pro unlocks:** deep linkage + architecture graph.

---

# 🚀 Pro Mode Unlocks
🔒 Full Component Tree  
🔒 Full API Route Map  
🔒 Controller–Service–Model Graph  
🔒 Circular Dependency Map  
🔒 Unused File Deep Scan  
🔒 Full Drift Timeline  
🔒 Ecosystem Multi-Project Intelligence  
🔒 AI-Generated Architecture Refactor Plan  

---

_Generated by Origin Lite Mode (Fullstack)_
`;

  return out;
}

export default generateFullstackSummary;
